<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6bp10jx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6bp10jx/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6bp10jx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6bp10jx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6bp10jx\appProdProjectContainer([
    'container.build_hash' => '6bp10jx',
    'container.build_id' => '5c52a8a4',
    'container.build_time' => 1629964727,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6bp10jx');
